language: python

python:
  - 3.6
  - 3.7
  - 3.8

install:
  - pip install -r requirements.txt
  - pip install --upgrade pycodestyle pytest pytest-cov
  - python setup.py notopspin

script:
  - pytest -v --cov=poptpy/poptpy_backend
