language: python

python:
  - 3.6
  - 3.7
  - 3.8

install:
  - pip install -r requirements.txt
  - pip install --upgrade pycodestyle pytest pytest-cov
  - pip install sphinx numpydoc
  - source docs/texlive/texlive.sh
  - python setup.py notopspin

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

script:
  - pytest -v --cov=nmrpoise/poise_backend
  - sphinx-build -b dirhtml docs docs/dirhtml
  - touch docs/dirhtml/.nojekyll
  - sphinx-build -a -E -b latex docs docs/latex
  - cd docs/latex
  - texliveonfly poise.tex
  - cp poise.pdf ../dirhtml
  - cd -

git:
  depth: 2

deploy:
  edge: true
  provider: pages
  github_token: $GITHUB_TOKEN
  local_dir: docs/dirhtml
  on:
    branch: master
    python: "3.8"
